### ISSUE TITLE
Format the timestamp in clash warnings

### ISSUE THREAD

**Issue by ColinRoitt** [UniversityRadioYork/off-air-studio-booking#2]
Format this so that it's more readable at a glance - ideally, follow the formatting on the calendar. Consider a jump to event button 

Currently reads as  2024-09-26 14:00:00 +0000 UTC. Should use local timecode formatting removing the timezone code at the end

![image](https://github.com/user-attachments/assets/aa3fd736-326c-471a-877d-34d820e35e2b)

**Comment by Kami-prog** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler

**Comment by miguellords** [comment]
This might help:This file might fix it
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by michael-grace** [comment]
_not this pointing out it's saying everything to UTC, despite actually being local time_
